<#
.SYNOPSIS
Generates a local CashLens environment file with random secrets.

.DESCRIPTION
Profiles:
  development   Copies apps/api/.env.example to apps/api/.env and replaces the
                random-secret placeholders (JWT_SECRET, EMAIL_TOKEN_ENCRYPTION_KEY,
                GMAIL_OAUTH_STATE_SECRET) with random values.
  release-test  Writes .env.release-test at the repository root with synthetic,
                release-safe values for every production setting, for use with
                `docker compose --env-file .env.release-test -f docker-compose.prod.yml`.
                The Gmail client values are synthetic and never work against Google.

Safety rules:
  * No generated value is ever printed.
  * A target inside the repository must be git-ignored, or the script refuses to write.
  * An existing file is never overwritten without -Force.

.EXAMPLE
./scripts/init-local-env.ps1

.EXAMPLE
./scripts/init-local-env.ps1 -Profile release-test -PublicOrigin https://cashlens-release.example.test
#>
[CmdletBinding()]
param(
  [ValidateSet('development', 'release-test')]
  [string]$Profile = 'development',

  [string]$PublicOrigin,

  [string]$OutFile,

  [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

function New-RandomSecret {
  param([int]$ByteCount = 48)
  $bytes = New-Object byte[] $ByteCount
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try { $rng.GetBytes($bytes) } finally { $rng.Dispose() }
  # base64url: safe inside URLs and env files, no quoting needed.
  return ([Convert]::ToBase64String($bytes)).TrimEnd('=').Replace('+', '-').Replace('/', '_')
}

function New-RandomHex {
  param([int]$ByteCount = 8)
  $bytes = New-Object byte[] $ByteCount
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try { $rng.GetBytes($bytes) } finally { $rng.Dispose() }
  return -join ($bytes | ForEach-Object { $_.ToString('x2') })
}

function Resolve-TargetPath {
  param([string]$Path)
  if ([System.IO.Path]::IsPathRooted($Path)) {
    return [System.IO.Path]::GetFullPath($Path)
  }
  return [System.IO.Path]::GetFullPath((Join-Path (Get-Location).Path $Path))
}

function Assert-SafeTarget {
  param([string]$Target)

  $rootWithSeparator = $repoRoot.TrimEnd('\', '/') + [System.IO.Path]::DirectorySeparatorChar
  $insideRepo = $Target.StartsWith($rootWithSeparator, [System.StringComparison]::OrdinalIgnoreCase)
  if ($insideRepo) {
    $relative = $Target.Substring($rootWithSeparator.Length).Replace('\', '/')
    & git -C $repoRoot check-ignore -q -- $relative
    if ($LASTEXITCODE -ne 0) {
      throw "Refusing to write '$relative': it is not git-ignored. Add it to .gitignore first."
    }
  }

  if ((Test-Path -LiteralPath $Target) -and -not $Force) {
    throw "Refusing to overwrite existing '$Target'. Re-run with -Force to replace it."
  }
}

function Write-EnvFile {
  param([string]$Target, [string[]]$Lines)
  $directory = Split-Path -Parent $Target
  if (-not (Test-Path -LiteralPath $directory)) {
    New-Item -ItemType Directory -Path $directory | Out-Null
  }
  # UTF-8 without BOM and LF endings, so dotenv and docker compose parse it cleanly.
  $content = ($Lines -join "`n") + "`n"
  [System.IO.File]::WriteAllText($Target, $content, (New-Object System.Text.UTF8Encoding($false)))
}

function Get-DevelopmentLines {
  $examplePath = Join-Path $repoRoot 'apps/api/.env.example'
  if (-not (Test-Path -LiteralPath $examplePath)) {
    throw "Missing $examplePath"
  }
  $randomKeys = @('JWT_SECRET', 'EMAIL_TOKEN_ENCRYPTION_KEY', 'GMAIL_OAUTH_STATE_SECRET')
  $generated = New-Object System.Collections.Generic.List[string]
  $lines = foreach ($line in (Get-Content -LiteralPath $examplePath)) {
    if ($line -match '^\s*([A-Z0-9_]+)=' -and $randomKeys -contains $Matches[1]) {
      $key = $Matches[1]
      $generated.Add($key)
      '{0}="{1}"' -f $key, (New-RandomSecret)
    }
    else {
      $line
    }
  }
  return @{ Lines = $lines; Generated = $generated }
}

function Get-ReleaseTestLines {
  if (-not $PublicOrigin) {
    throw '-PublicOrigin https://<release-test-host> is required for the release-test profile.'
  }
  $origin = $PublicOrigin.TrimEnd('/')
  if ($origin -notmatch '^https://[A-Za-z0-9.-]+(:\d{1,5})?$') {
    throw '-PublicOrigin must be an https origin without a path, for example https://cashlens-release.example.test'
  }

  $dbUser = 'cashlens'
  $dbName = 'cashlens_db'
  $dbPassword = New-RandomSecret -ByteCount 32
  $lines = @(
    '# Generated by scripts/init-local-env.ps1 -Profile release-test.',
    '# Synthetic, release-safe values for release verification only. Never commit this file.',
    'NODE_ENV=production',
    'PORT=3000',
    'LOG_LEVEL=info',
    "POSTGRES_USER=$dbUser",
    "POSTGRES_PASSWORD=$dbPassword",
    "POSTGRES_DB=$dbName",
    "DATABASE_URL=postgresql://${dbUser}:${dbPassword}@postgres:5432/${dbName}?schema=public",
    "JWT_SECRET=$(New-RandomSecret)",
    'JWT_EXPIRES_IN=15m',
    'JWT_REFRESH_EXPIRES_IN_DAYS=30',
    'COOKIE_SECURE=true',
    'COOKIE_SAME_SITE=lax',
    "CORS_ORIGIN=$origin",
    "APP_PUBLIC_URL=$origin",
    '# Starting value only: T100 verifies it covers the address the API observes behind the proxy.',
    'TRUST_PROXY=loopback,172.28.0.1',
    "EMAIL_TOKEN_ENCRYPTION_KEY=$(New-RandomSecret)",
    "GMAIL_CLIENT_ID=release-test-$(New-RandomHex).apps.googleusercontent.invalid",
    "GMAIL_CLIENT_SECRET=$(New-RandomSecret -ByteCount 24)",
    "GMAIL_REDIRECT_URI=$origin/api/email-connections/gmail/callback",
    "GMAIL_OAUTH_STATE_SECRET=$(New-RandomSecret)",
    'EMAIL_TRANSPORT=disabled'
  )
  $generated = @('POSTGRES_PASSWORD', 'DATABASE_URL', 'JWT_SECRET', 'EMAIL_TOKEN_ENCRYPTION_KEY',
    'GMAIL_CLIENT_ID', 'GMAIL_CLIENT_SECRET', 'GMAIL_OAUTH_STATE_SECRET')
  return @{ Lines = $lines; Generated = $generated }
}

if (-not $OutFile) {
  if ($Profile -eq 'release-test') {
    $OutFile = Join-Path $repoRoot '.env.release-test'
  }
  else {
    $OutFile = Join-Path $repoRoot 'apps/api/.env'
  }
}
$target = Resolve-TargetPath $OutFile
Assert-SafeTarget $target

if ($Profile -eq 'release-test') {
  $result = Get-ReleaseTestLines
}
else {
  $result = Get-DevelopmentLines
}

Write-EnvFile -Target $target -Lines $result.Lines
Write-Host "Wrote $target ($Profile profile)."
Write-Host ("Generated random values for: {0}. Values are not shown." -f ($result.Generated -join ', '))
