<#
.SYNOPSIS
Clean-checkout container release verification for CashLens (T100).

.DESCRIPTION
Builds and runs the production compose stack (docker-compose.prod.yml) with a
release-test env file, behind the operator's TLS reverse proxy, and checks
OPS-001-OPS-009, AUTH-003, SEC-009, CFG-006, and SC-013:

  1. Secret scan (scripts/scan-secrets.ps1) and migration matrix
     (apps/api/test/scripts/verify-migrations.ps1, against a disposable
     PostgreSQL container unless -MigrationAdminUrl is given).
  2. Compose configuration: API and web published on 127.0.0.1 only,
     PostgreSQL unpublished, pinned cashlens_net (172.28.0.0/24).
  3. Build, then `run --rm migrate` before the API starts.
  4. An http:// CORS_ORIGIN makes API startup fail.
  5. Through the proxy (https://<release-test-host>): the web app is served,
     its bundle calls the relative /api with no absolute API origin,
     /api/health/ready returns 200, login sets Secure; HttpOnly; SameSite=Lax
     cookies, and an authenticated same-origin call with them succeeds.
  6. TRUST_PROXY: the peer address the API logged (`req.remoteAddress`) for a
     request sent through the proxy must be covered by TRUST_PROXY. The
     observed address and TRUST_PROXY are recorded.
  7. Direct loopback login without forwarded headers returns 403
     HTTPS_REQUIRED; loopback /api/health/ready returns 200.
  8. Admin bootstrap (SEC-009), an idempotent rerun, and the upgrade review:
     `--list-admins` is recorded and an unapproved administrator on the
     existing database is revoked.
  9. Restart and persistence: after an API restart and a full `down`/`up`
     (volumes kept), the account and exactly one copy of a transaction remain.
 10. Dependency outage: with PostgreSQL stopped, readiness and data calls
     return 503; both recover when it starts again.
 11. Graceful shutdown: SIGTERM stops the API within its grace period and it
     logs the graceful shutdown.

Where it runs. The result is AUTHORITATIVE only on the reference release host
(plan.md "Reference release host and release-test profile"): Linux, Docker
Engine (not Docker Desktop), the documented proxy terminating TLS, and
-ReferenceHost with -HostDescription given. Anywhere else, including Docker
Desktop, every check still runs but the result is INFORMATIVE and is never the
release gate.

Host state. The script needs only Docker with compose v2, git, curl, node, the
env file, and a running proxy for the public origin. It never deletes a volume:
the stack's PostgreSQL volume (<project>_cashlens_prod_postgres_data) is kept
between runs, and `down` is called without -v. The disposable migration-check
PostgreSQL container has no named volume and is removed on exit. Nothing
secret is printed: env values other than origins, ports, and TRUST_PROXY are
never echoed, and all identities are synthetic (@example.test).

Exit codes: 0 all checks passed on the reference host (authoritative);
3 all checks passed on another host (informative only, not the release gate);
1 a check failed; 2 a prerequisite is missing.

.PARAMETER EnvFile
Release-test env file. Default: .env.release-test at the repository root,
generated by ./scripts/init-local-env.ps1 -Profile release-test -PublicOrigin
https://<release-test-host>. API_HOST_PORT and WEB_HOST_PORT may be added to it
when the defaults (3000, 8080) are taken on the host.

.PARAMETER PublicOrigin
The https origin the proxy serves. Default: CORS_ORIGIN from the env file.

.PARAMETER ProxyAddress
Optional IP address that the public host name resolves to (passed to curl
--resolve), for release-test host names without DNS. Nothing on the host is
changed.

.PARAMETER CaCert
PEM file of the test CA that signed the proxy certificate. Default:
$env:NODE_EXTRA_CA_CERTS; otherwise the system trust store is used.

.PARAMETER ProjectName
Compose project name. Default: cashlens-release-check. Only one stack using
docker-compose.prod.yml can run on a host at a time (pinned subnet).

.PARAMETER MigrationAdminUrl
postgresql:// maintenance URL for the migration matrix. Default: a disposable
postgres:16-alpine container on a free loopback port.

.PARAMETER SecretScanBaseRef
Passed to scan-secrets.ps1 as -BaseRef when given.

.PARAMETER ReferenceHost
Claims the run is on the reference release host. It is honoured only on Linux
with Docker Engine and with -HostDescription.

.PARAMETER HostDescription
Reference host description for release evidence (for example
"CI runner, Ubuntu 24.04, 2 vCPU, 4 GB, SSD").

.PARAMETER SkipBuild
Uses the already built release images.

.PARAMETER KeepRunning
Leaves the stack running at the end (default: `down`, volumes kept).

.EXAMPLE
./scripts/verify-release.ps1 -ReferenceHost -HostDescription "CI runner, Ubuntu 24.04, 2 vCPU, 4 GB, SSD"

.EXAMPLE
./scripts/verify-release.ps1 -ProxyAddress 127.0.0.1 -CaCert ./tmp/test-ca.pem
#>
[CmdletBinding()]
param(
  [string]$EnvFile,
  [string]$PublicOrigin,
  [string]$ProxyAddress,
  [string]$CaCert,
  [string]$ProjectName = 'cashlens-release-check',
  [string]$MigrationAdminUrl,
  [string]$SecretScanBaseRef,
  [switch]$ReferenceHost,
  [string]$HostDescription,
  [switch]$SkipBuild,
  [switch]$KeepRunning
)
# 'Continue': Windows PowerShell 5.1 turns native stderr into terminating errors under 'Stop'.
$ErrorActionPreference = 'Continue'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$composeFile = Join-Path $repoRoot 'docker-compose.prod.yml'
if (-not $EnvFile) { $EnvFile = Join-Path $repoRoot '.env.release-test' }
$runId = '{0}{1}' -f [DateTime]::UtcNow.ToString('yyMMddHHmmss'), (Get-Random -Minimum 1000 -Maximum 9999)
$workDir = Join-Path ([IO.Path]::GetTempPath()) "cashlens-verify-release-$runId"
$null = New-Item -ItemType Directory -Force -Path $workDir
# The work directory holds the session cookie jar; keep it private on shared hosts.
if ($env:OS -ne 'Windows_NT') { & chmod 700 $workDir }
$psExe = (Get-Process -Id $PID).Path
$onWindows = ($env:OS -eq 'Windows_NT')
$curl = if ($onWindows) { 'curl.exe' } else { 'curl' }
$utf8 = New-Object Text.UTF8Encoding $false
$script:schannel = [bool]((& $curl -V 2>$null | Out-String) -match 'Schannel')

$results = New-Object System.Collections.Generic.List[object]
$evidence = [ordered]@{}
$cleanup = New-Object System.Collections.Generic.List[scriptblock]

function Add-Result([string]$Check, [bool]$Pass, [string]$Detail = '') {
  $results.Add([pscustomobject]@{ Check = $Check; Result = $(if ($Pass) { 'PASS' } else { 'FAIL' }); Detail = $Detail })
  Write-Host ('[{0}] {1}{2}' -f $(if ($Pass) { 'PASS' } else { 'FAIL' }), $Check, $(if ($Detail) { " - $Detail" } else { '' }))
}

function Exit-Prerequisite([string]$Message) {
  Write-Host "PREREQUISITE: $Message"
  Remove-Item -Recurse -Force $workDir -ErrorAction SilentlyContinue
  exit 2
}

function Get-Prop($Object, [string]$Name) {
  if ($null -eq $Object) { return $null }
  $property = $Object.PSObject.Properties[$Name]
  if ($property) { return $property.Value }
  return $null
}

# --- env file (values are read, never printed except origins/ports/TRUST_PROXY)
function Read-EnvFile([string]$Path) {
  $values = @{}
  foreach ($line in [IO.File]::ReadAllLines($Path)) {
    if ($line -match '^\s*#' -or $line -notmatch '=') { continue }
    $key, $value = $line -split '=', 2
    $values[$key.Trim()] = $value.Trim().Trim('"').Trim("'")
  }
  return $values
}

function Invoke-Compose {
  # Output is returned to the caller, never echoed: `config` resolves secrets.
  & docker compose -p $ProjectName --env-file $EnvFile -f $composeFile @args 2>&1 | ForEach-Object { "$_" }
}

function Wait-Until([scriptblock]$Condition, [int]$TimeoutSeconds, [int]$IntervalSeconds = 2) {
  $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
  do {
    if (& $Condition) { return $true }
    Start-Sleep -Seconds $IntervalSeconds
  } while ((Get-Date) -lt $deadline)
  return [bool](& $Condition)
}

# --- HTTP through curl (TLS verification always on; --resolve only for the public origin)
function Invoke-Http {
  param(
    [string]$Url,
    [string]$Method = 'GET',
    [string]$Body,
    [string]$CookieJar,
    [string[]]$Header = @(),
    [string]$Resolve
  )
  $bodyFile = Join-Path $workDir ('body-{0}.txt' -f [guid]::NewGuid().ToString('N'))
  $headFile = Join-Path $workDir ('head-{0}.txt' -f [guid]::NewGuid().ToString('N'))
  $arguments = @('-sS', '-o', $bodyFile, '-D', $headFile, '-w', '%{http_code}', '-X', $Method, '--max-time', '30')
  if ($Url.StartsWith($script:origin)) {
    if ($CaCert) { $arguments += @('--cacert', $CaCert) }
    if ($script:resolve) { $arguments += @('--resolve', $script:resolve) }
    # Windows' Schannel curl also demands a revocation answer, which a local
    # test CA cannot give; the certificate chain is still verified.
    if ($script:schannel) { $arguments += '--ssl-no-revoke' }
  }
  if ($PSBoundParameters.ContainsKey('Body')) {
    $inFile = Join-Path $workDir ('in-{0}.json' -f [guid]::NewGuid().ToString('N'))
    [IO.File]::WriteAllText($inFile, $Body, $utf8)
    $arguments += @('-H', 'Content-Type: application/json', '--data-binary', "@$inFile")
  }
  if ($Resolve) { $arguments += @('--resolve', $Resolve) }
  if ($CookieJar) { $arguments += @('-b', $CookieJar, '-c', $CookieJar) }
  foreach ($h in $Header) { $arguments += @('-H', $h) }
  $code = (& $curl @arguments $Url 2>&1 | Out-String).Trim()
  $status = 0
  if ($code -match '(\d{3})$') { $status = [int]$Matches[1] }
  $response = [pscustomobject]@{
    Status  = $status
    Headers = $(if (Test-Path $headFile) { [IO.File]::ReadAllText($headFile) } else { '' })
    Body    = $(if (Test-Path $bodyFile) { [IO.File]::ReadAllText($bodyFile, $utf8) } else { '' })
    Error   = $(if ($status -eq 0) { (@($code -split "`r?`n" | Where-Object { $_ -match 'curl: \(' }) + $code)[0] } else { '' })
  }
  Remove-Item -Force $bodyFile, $headFile -ErrorAction SilentlyContinue
  return $response
}

function ConvertFrom-JsonSafe([string]$Text) {
  try { return ($Text | ConvertFrom-Json) } catch { return $null }
}

function Get-ErrorCode($Response) {
  return Get-Prop (ConvertFrom-JsonSafe $Response.Body) 'code'
}

# --- TRUST_PROXY coverage, mirroring Express/proxy-addr keywords, IPs, and CIDRs
function ConvertTo-IpAddress([string]$Text) {
  $value = $Text.Trim()
  if ($value -match '^::ffff:(\d+\.\d+\.\d+\.\d+)$') { $value = $Matches[1] }
  $address = $null
  if ([Net.IPAddress]::TryParse($value, [ref]$address)) { return $address }
  return $null
}

function Test-InRange([Net.IPAddress]$Address, [string]$Range) {
  $network, $prefixText = $Range -split '/', 2
  $net = ConvertTo-IpAddress $network
  if ($null -eq $net -or $net.AddressFamily -ne $Address.AddressFamily) { return $false }
  $a = $Address.GetAddressBytes()
  $b = $net.GetAddressBytes()
  $prefix = if ($prefixText) { [int]$prefixText } else { $a.Length * 8 }
  for ($bit = 0; $bit -lt $prefix; $bit++) {
    $byte = [math]::Floor($bit / 8)
    $mask = 0x80 -shr ($bit % 8)
    if (($a[$byte] -band $mask) -ne ($b[$byte] -band $mask)) { return $false }
  }
  return $true
}

function Test-TrustProxyCovers([string]$TrustProxy, [string]$Observed) {
  $address = ConvertTo-IpAddress $Observed
  if ($null -eq $address) { return $false }
  $keywords = @{
    loopback    = @('127.0.0.0/8', '::1/128')
    linklocal   = @('169.254.0.0/16', 'fe80::/10')
    uniquelocal = @('10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16', 'fc00::/7')
  }
  foreach ($token in ($TrustProxy -split ',')) {
    $t = $token.Trim()
    $ranges = if ($keywords.ContainsKey($t)) { $keywords[$t] } else { @($t) }
    foreach ($range in $ranges) {
      if (Test-InRange $address $range) { return $true }
    }
  }
  return $false
}

function Get-ApiLogLines {
  return @(Invoke-Compose logs --no-color --no-log-prefix api)
}

# ---------------------------------------------------------------------------
# Prerequisites and host classification
# ---------------------------------------------------------------------------
foreach ($tool in @('docker', 'git', 'node', $curl)) {
  if (-not (Get-Command $tool -ErrorAction SilentlyContinue)) { Exit-Prerequisite "$tool is not on PATH" }
}
& docker compose version *> $null
if ($LASTEXITCODE -ne 0) { Exit-Prerequisite 'docker compose v2 is required' }
if (-not (Test-Path $EnvFile)) {
  Exit-Prerequisite "env file not found: $EnvFile (./scripts/init-local-env.ps1 -Profile release-test -PublicOrigin https://<release-test-host>)"
}
$EnvFile = (Resolve-Path $EnvFile).Path
if ($CaCert) { $CaCert = (Resolve-Path $CaCert).Path }
elseif ($env:NODE_EXTRA_CA_CERTS -and (Test-Path $env:NODE_EXTRA_CA_CERTS)) { $CaCert = (Resolve-Path $env:NODE_EXTRA_CA_CERTS).Path }

$envValues = Read-EnvFile $EnvFile
if (-not $PublicOrigin) { $PublicOrigin = $envValues['CORS_ORIGIN'] }
$PublicOrigin = "$PublicOrigin".TrimEnd('/')
if ($PublicOrigin -notmatch '^https://[^/]+$') { Exit-Prerequisite "the public origin must be an https origin without a path (got '$PublicOrigin')" }
$script:origin = $PublicOrigin
$originUri = [Uri]$PublicOrigin
$script:resolve = if ($ProxyAddress) { '{0}:{1}:{2}' -f $originUri.Host, $originUri.Port, $ProxyAddress } else { $null }
$apiPort = if ($envValues['API_HOST_PORT']) { $envValues['API_HOST_PORT'] } else { '3000' }
$webPort = if ($envValues['WEB_HOST_PORT']) { $envValues['WEB_HOST_PORT'] } else { '8080' }
$trustProxy = ''  # read from the resolved compose configuration (step 2)
$loopbackApi = "http://127.0.0.1:$apiPort/api"

$dockerOs = (& docker info --format '{{.OperatingSystem}}' 2>$null | Out-String).Trim()
$dockerCpus = (& docker info --format '{{.NCPU}}' 2>$null | Out-String).Trim()
$dockerMem = (& docker info --format '{{.MemTotal}}' 2>$null | Out-String).Trim()
$isLinuxHost = ($PSVersionTable.PSEdition -eq 'Core') -and [bool](Get-Variable IsLinux -ValueOnly -ErrorAction SilentlyContinue)
$memGb = if ($dockerMem -match '^\d+$') { [math]::Round([double]$dockerMem / 1GB, 1) } else { 0 }
$dirty = (& git -C $repoRoot status --porcelain 2>$null | Measure-Object).Count
$reasons = @()
if (-not $ReferenceHost) { $reasons += '-ReferenceHost was not given' }
if (-not $isLinuxHost) { $reasons += 'the host is not Linux' }
if ($dockerOs -match 'Docker Desktop') { $reasons += "Docker Desktop ($dockerOs), not Docker Engine" }
if (-not $HostDescription) { $reasons += 'no -HostDescription' }
# The gate is a clean checkout built by this run on a host of at least 2 vCPU and 4 GB.
if ($dirty -gt 0) { $reasons += "$dirty uncommitted path(s): not a clean checkout" }
if ($SkipBuild) { $reasons += '-SkipBuild reuses images this run did not build' }
if (-not ($dockerCpus -match '^\d+$' -and [int]$dockerCpus -ge 2)) { $reasons += "fewer than 2 vCPU ($dockerCpus)" }
if ($memGb -lt 3.5) { $reasons += "less than 4 GB of memory ($memGb GB visible to Docker)" }
$authoritative = ($reasons.Count -eq 0)
$evidence['mode'] = $(if ($authoritative) { 'AUTHORITATIVE (reference release host)' } else { 'INFORMATIVE (' + ($reasons -join '; ') + ')' })
$evidence['host'] = ('{0}; docker: {1}, {2} CPU, {3} GB{4}' -f [Environment]::OSVersion.VersionString, $dockerOs, $dockerCpus, $memGb, $(if ($HostDescription) { "; $HostDescription" } else { '' }))
$evidence['publicOrigin'] = $PublicOrigin
$evidence['loopbackPorts'] = "api 127.0.0.1:$apiPort, web 127.0.0.1:$webPort"
$evidence['commit'] = (& git -C $repoRoot rev-parse --short HEAD 2>$null | Out-String).Trim()
$evidence['workingTree'] = $(if ($dirty -eq 0) { 'clean' } else { "$dirty uncommitted path(s): not a clean checkout" })
Write-Host "Mode: $($evidence['mode'])"
Write-Host "Host: $($evidence['host'])"
Write-Host "Origin: $PublicOrigin; compose project: $ProjectName; commit $($evidence['commit']) ($($evidence['workingTree']))"

# Never touch a deployment: the check runs only as its own, not yet running project.
if ($ProjectName -eq 'cashlens-prod') { Exit-Prerequisite "-ProjectName cashlens-prod is the deployment project name; use a dedicated check project" }
$existing = @(& docker compose -p $ProjectName --env-file $EnvFile -f $composeFile ps -a -q 2>$null | Where-Object { $_ })
if ($existing.Count -gt 0) {
  Exit-Prerequisite "compose project '$ProjectName' already has $($existing.Count) container(s); stop it first (docker compose -p $ProjectName ... down, volumes are kept)"
}

# The env file must stay out of git (CFG-006). A file outside the repository cannot be committed.
$envInRepo = $EnvFile.StartsWith($repoRoot, [StringComparison]::OrdinalIgnoreCase)
& git -C $repoRoot check-ignore -q $EnvFile 2>$null
$ignored = (-not $envInRepo) -or ($LASTEXITCODE -eq 0)
$tracked = $false
if ($envInRepo) {
  & git -C $repoRoot ls-files --error-unmatch $EnvFile *> $null
  $tracked = ($LASTEXITCODE -eq 0)
}
Add-Result 'env file ignored and untracked' ($ignored -and -not $tracked) ("in repository=$envInRepo ignored=$ignored tracked=$tracked")
Add-Result 'env file is production' ($envValues['NODE_ENV'] -eq 'production' -and $envValues['CORS_ORIGIN'] -like 'https://*') ("NODE_ENV=$($envValues['NODE_ENV']), CORS_ORIGIN=$($envValues['CORS_ORIGIN']), EMAIL_TRANSPORT=$($envValues['EMAIL_TRANSPORT'])")

$userEmail = "release-check-$runId@example.test"
$legacyEmail = "release-legacy-admin-$runId@example.test"
$password = 'Rc-' + [guid]::NewGuid().ToString('N') + '!9'
$apiContainerStopped = $false

try {
  # -------------------------------------------------------------------------
  # 1. Secret scan and migration matrix (reused scripts)
  # -------------------------------------------------------------------------
  $scanArgs = @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', (Join-Path $repoRoot 'scripts/scan-secrets.ps1'))
  if ($SecretScanBaseRef) { $scanArgs += @('-BaseRef', $SecretScanBaseRef) }
  $scanOut = & $psExe @scanArgs 2>&1 | ForEach-Object { "$_" }
  $scanExit = $LASTEXITCODE
  $evidence['secretScan'] = (($scanOut | Where-Object { $_ -match 'gitleaks|Working tree|History|exceptions' }) -join ' | ')
  Add-Result 'secret scan (scan-secrets.ps1)' ($scanExit -eq 0) ("exit $scanExit")
  if ($scanExit -ne 0) { $scanOut | Select-Object -Last 20 | ForEach-Object { Write-Host "  $_" } }

  $adminUrl = $MigrationAdminUrl
  if (-not $adminUrl) {
    $listener = New-Object Net.Sockets.TcpListener ([Net.IPAddress]::Loopback, 0)
    $listener.Start(); $pgPort = $listener.LocalEndpoint.Port; $listener.Stop()
    $pgName = "$ProjectName-migrations-$runId"
    $pgPassword = [guid]::NewGuid().ToString('N')
    # Disposable server for the migration matrix: no named volume, removed on exit.
    & docker run -d --rm --name $pgName -e POSTGRES_USER=migration_check -e "POSTGRES_PASSWORD=$pgPassword" -e POSTGRES_DB=postgres -p "127.0.0.1:${pgPort}:5432" postgres:16-alpine *> $null
    if ($LASTEXITCODE -ne 0) { Exit-Prerequisite 'could not start the disposable PostgreSQL container for the migration matrix' }
    $cleanup.Add({ & docker rm -f $pgName *> $null }.GetNewClosure())
    $ready = Wait-Until { & docker exec $pgName pg_isready -U migration_check -d postgres *> $null; $LASTEXITCODE -eq 0 } 60
    Start-Sleep -Seconds 2
    if (-not $ready) { Exit-Prerequisite 'the disposable PostgreSQL container did not become ready' }
    $adminUrl = "postgresql://migration_check:$pgPassword@127.0.0.1:$pgPort/postgres"
  }
  # Passed through the environment, never on a command line that `ps` shows.
  $previousAdminUrl = $env:MIGRATION_CHECK_ADMIN_URL
  $env:MIGRATION_CHECK_ADMIN_URL = $adminUrl
  $migrationOut = & $psExe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $repoRoot 'apps/api/test/scripts/verify-migrations.ps1') 2>&1 | ForEach-Object { "$_" }
  $migrationExit = $LASTEXITCODE
  $env:MIGRATION_CHECK_ADMIN_URL = $previousAdminUrl
  # Greedy up to the last '@' of the URL, so a password containing '@' is fully hidden.
  $hideUrlPassword = { param($text) $text -replace '://([^:/@\s]+):\S*@', '://$1:***@' }
  $evidence['migrations'] = & $hideUrlPassword ((($migrationOut | Where-Object { $_ -match '\b(PASS|FAIL)\b' } | ForEach-Object { ($_ -replace '\s{2,}', ' ').Trim() }) -join ' | '))
  Add-Result 'migration matrix (verify-migrations.ps1)' ($migrationExit -eq 0) ("exit $migrationExit")
  if ($migrationExit -ne 0) { $migrationOut | Select-Object -Last 20 | ForEach-Object { Write-Host "  $(& $hideUrlPassword $_)" } }

  # -------------------------------------------------------------------------
  # 2. Compose configuration (parsed in memory; it contains resolved secrets)
  # -------------------------------------------------------------------------
  $configJson = (& docker compose -p $ProjectName --env-file $EnvFile -f $composeFile config --format json 2>$null | Out-String)
  $config = ConvertFrom-JsonSafe $configJson
  $configJson = $null
  if ($null -eq $config) {
    Add-Result 'compose config' $false 'docker compose config failed (a required variable is missing from the env file?)'
    throw 'compose config failed'
  }
  $services = Get-Prop $config 'services'
  $bindings = @()
  $loopbackOnly = $true
  foreach ($name in @('api', 'web')) {
    $ports = @(Get-Prop (Get-Prop $services $name) 'ports')
    if ($ports.Count -eq 0) { $loopbackOnly = $false }
    foreach ($p in $ports) {
      $bindings += '{0}={1}:{2}' -f $name, (Get-Prop $p 'host_ip'), (Get-Prop $p 'published')
      if ((Get-Prop $p 'host_ip') -ne '127.0.0.1') { $loopbackOnly = $false }
    }
  }
  $pgPorts = @(Get-Prop (Get-Prop $services 'postgres') 'ports') | Where-Object { $_ }
  $subnet = @(Get-Prop (Get-Prop (Get-Prop (Get-Prop $config 'networks') 'cashlens_net') 'ipam') 'config') | ForEach-Object { Get-Prop $_ 'subnet' }
  $pinned = ($subnet -contains '172.28.0.0/24')
  $servicesOnNet = @('postgres', 'migrate', 'api', 'web') | Where-Object {
    $networks = Get-Prop (Get-Prop $services $_) 'networks'
    ($null -ne $networks) -and (($networks -is [array] -and $networks -contains 'cashlens_net') -or $null -ne $networks.PSObject.Properties['cashlens_net'])
  }
  Add-Result 'config: API and web on 127.0.0.1 only' $loopbackOnly ($bindings -join ', ')
  Add-Result 'config: PostgreSQL unpublished' (@($pgPorts).Count -eq 0) ("published ports: $(@($pgPorts).Count)")
  Add-Result 'config: pinned cashlens_net' ($pinned -and @($servicesOnNet).Count -eq 4) ("subnet $($subnet -join ','); services on it: $($servicesOnNet -join ',')")
  # What the API container will actually run with (shell variables override the
  # env file, and the compose file has defaults): only these three keys are read.
  $apiEnvironment = Get-Prop (Get-Prop $services 'api') 'environment'
  $trustProxy = [string](Get-Prop $apiEnvironment 'TRUST_PROXY')
  $effectiveNodeEnv = [string](Get-Prop $apiEnvironment 'NODE_ENV')
  $effectiveCors = [string](Get-Prop $apiEnvironment 'CORS_ORIGIN')
  Add-Result 'config: API runs in production with the public https origin' ($effectiveNodeEnv -eq 'production' -and $effectiveCors -eq $PublicOrigin) ("NODE_ENV=$effectiveNodeEnv, CORS_ORIGIN=$effectiveCors, TRUST_PROXY=$trustProxy")
  $apiEnvironment = $null; $config = $null; $services = $null

  # -------------------------------------------------------------------------
  # 3. Build and migrate before the API starts
  # -------------------------------------------------------------------------
  if (-not $SkipBuild) {
    $buildOut = Invoke-Compose build
    Add-Result 'build release images' ($LASTEXITCODE -eq 0) ("exit $LASTEXITCODE")
    if ($LASTEXITCODE -ne 0) { $buildOut | Select-Object -Last 30 | ForEach-Object { Write-Host "  $_" }; throw 'build failed' }
  }
  $migrateOut = Invoke-Compose run --rm migrate
  $migrateExit = $LASTEXITCODE
  $evidence['migrate'] = (($migrateOut | Where-Object { $_ -match 'applied|No pending' }) | Select-Object -Last 1) -join ' | '
  Add-Result 'run --rm migrate (before api)' ($migrateExit -eq 0) ("exit $migrateExit")
  if ($migrateExit -ne 0) { $migrateOut | Select-Object -Last 20 | ForEach-Object { Write-Host "  $_" }; throw 'migrate failed' }

  # -------------------------------------------------------------------------
  # 4. An http:// CORS_ORIGIN makes startup fail
  # -------------------------------------------------------------------------
  $probe = "$ProjectName-cors-probe-$runId"
  $cleanup.Add({ & docker rm -f $probe *> $null }.GetNewClosure())
  $null = Invoke-Compose run -d --no-deps --name $probe -e CORS_ORIGIN=http://insecure-origin.example.test api
  $stopped = Wait-Until { ((& docker inspect -f '{{.State.Running}}' $probe 2>$null | Out-String).Trim()) -eq 'false' } 60
  $probeExit = (& docker inspect -f '{{.State.ExitCode}}' $probe 2>$null | Out-String).Trim()
  $probeLog = (& docker logs $probe 2>&1 | Out-String)
  & docker rm -f $probe *> $null
  $rejected = $stopped -and $probeExit -ne '0' -and $probeLog -match 'app\.start_failed' -and $probeLog -match 'CORS_ORIGIN'
  Add-Result 'http:// CORS_ORIGIN rejected at startup' $rejected ("stopped=$stopped exit=$probeExit")

  # -------------------------------------------------------------------------
  # 5. Start the stack; loopback health
  # -------------------------------------------------------------------------
  $upOut = Invoke-Compose up -d
  if ($LASTEXITCODE -ne 0) { $upOut | Select-Object -Last 20 | ForEach-Object { Write-Host "  $_" } }
  $healthy = Wait-Until { (Invoke-Http "$loopbackApi/health/ready").Status -eq 200 } 180 3
  Add-Result 'loopback http /api/health/ready = 200' $healthy
  if (-not $healthy) { throw 'the API did not become ready' }
  $null = Wait-Until { (Invoke-Http "$PublicOrigin/").Status -eq 200 } 60 3

  # The kept volume may still hold synthetic administrators of an earlier,
  # aborted run; they would make the bootstrap refuse (one administrator only).
  $bootstrap = 'dist/src/scripts/bootstrap-admin.js'
  $synthetic = '(release-check|release-legacy-admin)-\d+@example\.test'
  $leftovers = @(Invoke-Compose exec -T api node $bootstrap --list-admins | ForEach-Object { [regex]::Match($_, $synthetic).Value } | Where-Object { $_ } | Select-Object -Unique)
  foreach ($email in $leftovers) { $null = Invoke-Compose exec -T api node $bootstrap --revoke --email $email }
  $otherAdmins = @(Invoke-Compose exec -T api node $bootstrap --list-admins | Where-Object { $_ -match '@' })
  $evidence['adminsBeforeCheck'] = "synthetic leftovers revoked: $($leftovers.Count); other administrators: $($otherAdmins.Count)"
  Add-Result 'no administrator before the bootstrap check' ($otherAdmins.Count -eq 0) ("leftover synthetic admins revoked: $($leftovers.Count); remaining: $($otherAdmins.Count)$(if ($otherAdmins.Count) { ' (the release-test database already has an administrator; use a fresh check project)' })")

  # -------------------------------------------------------------------------
  # 6. Through the proxy: web app, bundle, readiness
  # -------------------------------------------------------------------------
  $index = Invoke-Http "$PublicOrigin/"
  Add-Result 'https / serves the web app' ($index.Status -eq 200 -and $index.Body -match 'id="root"') ("status $($index.Status)$(if ($index.Error) { ': ' + $index.Error })")
  $scripts = @([regex]::Matches($index.Body, 'src="(/assets/[^"]+\.js)"') | ForEach-Object { $_.Groups[1].Value })
  $checked = New-Object System.Collections.Generic.HashSet[string]
  $queue = New-Object System.Collections.Generic.Queue[string]
  foreach ($s in $scripts) { $queue.Enqueue($s) }
  $relativeApi = $false; $absolute = @()
  while ($queue.Count -gt 0 -and $checked.Count -lt 60) {
    $path = $queue.Dequeue()
    if (-not $checked.Add($path)) { continue }
    $chunk = (Invoke-Http "$PublicOrigin$path").Body
    if ($chunk -match '["''`]/api["''`/]') { $relativeApi = $true }
    $absolute += @([regex]::Matches($chunk, 'https?://[A-Za-z0-9.\-]+(?::\d+)?/api\b') | ForEach-Object { $_.Value })
    if ($chunk -match 'localhost:(3000|13000)|127\.0\.0\.1:3000') { $absolute += $Matches[0] }
    foreach ($m in [regex]::Matches($chunk, '(?:/assets/|\./)([A-Za-z0-9_\-.]+\.js)')) { $queue.Enqueue('/assets/' + $m.Groups[1].Value) }
  }
  $absolute = @($absolute | Select-Object -Unique)
  $unchecked = $queue.Count  # never pass on a partially scanned bundle
  Add-Result 'bundle uses relative /api, no absolute API origin' ($scripts.Count -gt 0 -and $relativeApi -and $absolute.Count -eq 0 -and $unchecked -eq 0) ("chunks $($checked.Count), unchecked $unchecked; relative /api=$relativeApi; absolute: $(if ($absolute.Count) { $absolute -join ', ' } else { 'none' })")
  $hsts = [bool]($index.Headers -match '(?im)^strict-transport-security:\s*max-age=\d+')
  $plainUri = 'http://{0}/' -f $originUri.Host
  $plainResolve = if ($ProxyAddress) { '{0}:80:{1}' -f $originUri.Host, $ProxyAddress } else { $null }
  $plain = Invoke-Http $plainUri -Resolve $plainResolve
  $location = [regex]::Match($plain.Headers, '(?im)^location:\s*(\S+)').Groups[1].Value
  Add-Result 'proxy: HSTS on https, http redirects to https' ($hsts -and $plain.Status -in 301, 308 -and $location -like "$PublicOrigin/*") ("hsts=$hsts; http status $($plain.Status) -> $location")
  $proxyReady = Invoke-Http "$PublicOrigin/api/health/ready"
  Add-Result 'https /api/health/ready = 200 through the proxy' ($proxyReady.Status -eq 200) ("status $($proxyReady.Status)")

  # -------------------------------------------------------------------------
  # 7. Login through the proxy: cookie attributes and an authenticated call
  # -------------------------------------------------------------------------
  $jar = Join-Path $workDir 'cookies.txt'
  $credentials = @{ email = $userEmail; password = $password } | ConvertTo-Json -Compress
  $register = Invoke-Http "$PublicOrigin/api/auth/register" -Method POST -Body (@{ email = $userEmail; password = $password; fullName = 'Release Check' } | ConvertTo-Json -Compress)
  Add-Result 'register through the proxy' ($register.Status -eq 201) ("status $($register.Status)")
  $login = Invoke-Http "$PublicOrigin/api/auth/login" -Method POST -Body $credentials -CookieJar $jar
  $setCookies = @($login.Headers -split "`r?`n" | Where-Object { $_ -match '^set-cookie:' })
  $badCookies = @($setCookies | Where-Object { $_ -notmatch ';\s*Secure(;|$)' -or $_ -notmatch ';\s*HttpOnly(;|$)' -or $_ -notmatch ';\s*SameSite=Lax(;|$)' })
  $cookieNames = ($setCookies | ForEach-Object { ($_ -replace '^set-cookie:\s*', '') -replace '=.*$', '' }) -join ', '
  $missingCookies = @('accessToken', 'refreshToken' | Where-Object { ($cookieNames -split ', ') -notcontains $_ })
  Add-Result 'login sets Secure; HttpOnly; SameSite=Lax cookies' ($login.Status -eq 200 -and $missingCookies.Count -eq 0 -and $badCookies.Count -eq 0) ("status $($login.Status); cookies: $cookieNames$(if ($missingCookies.Count) { '; missing: ' + ($missingCookies -join ', ') })")
  $me = Invoke-Http "$PublicOrigin/api/auth/me" -CookieJar $jar
  Add-Result 'authenticated same-origin call with the cookies' ($me.Status -eq 200) ("GET /api/auth/me status $($me.Status)")

  # -------------------------------------------------------------------------
  # 8. TRUST_PROXY covers the peer address the API observes behind the proxy
  # -------------------------------------------------------------------------
  $nonce = "trust-proxy-$runId"
  $probeResponse = Invoke-Http "$PublicOrigin/api/release-check/$nonce"
  $observed = $null; $forwardedSecure = $null
  $null = Wait-Until {
    foreach ($line in (Get-ApiLogLines | Where-Object { $_ -like "*$nonce*" })) {
      $entry = ConvertFrom-JsonSafe $line
      $address = Get-Prop (Get-Prop $entry 'req') 'remoteAddress'
      if ($address) { $script:observed = $address; return $true }
    }
    return $false
  } 20
  $covered = [bool]($observed -and (Test-TrustProxyCovers $trustProxy $observed))
  $evidence['trustProxy'] = "observed remoteAddress=$observed; TRUST_PROXY=$trustProxy; covered=$covered"
  Add-Result 'TRUST_PROXY covers the observed proxy peer' $covered ("remoteAddress=$(if ($observed) { $observed } else { 'not found in the API log' }); TRUST_PROXY=$trustProxy; probe status $($probeResponse.Status)")

  # -------------------------------------------------------------------------
  # 9. Direct loopback login without forwarded headers is refused
  # -------------------------------------------------------------------------
  $direct = Invoke-Http "$loopbackApi/auth/login" -Method POST -Body $credentials
  $directCookies = @($direct.Headers -split "`r?`n" | Where-Object { $_ -match '^set-cookie:' }).Count
  Add-Result 'direct http login = 403 HTTPS_REQUIRED' ($direct.Status -eq 403 -and (Get-ErrorCode $direct) -eq 'HTTPS_REQUIRED' -and $directCookies -eq 0) ("status $($direct.Status), code $(Get-ErrorCode $direct), cookies $directCookies")

  # -------------------------------------------------------------------------
  # 10. Admin bootstrap, idempotent rerun, and the upgrade review
  # -------------------------------------------------------------------------
  $first = Invoke-Compose exec -T api node $bootstrap --email $userEmail
  $firstExit = $LASTEXITCODE
  $again = Invoke-Compose exec -T api node $bootstrap --email $userEmail
  $againExit = $LASTEXITCODE
  Add-Result 'admin bootstrap' ($firstExit -eq 0) ("exit ${firstExit}: $(($first | Select-Object -Last 1))")
  Add-Result 'admin bootstrap rerun is idempotent' ($againExit -eq 0) ("exit ${againExit}: $(($again | Select-Object -Last 1))")

  # An administrator nobody approved, as an upgraded database may contain.
  $legacy = Invoke-Http "$PublicOrigin/api/auth/register" -Method POST -Body (@{ email = $legacyEmail; password = $password; fullName = 'Legacy Admin' } | ConvertTo-Json -Compress)
  $sql = "UPDATE ""User"" SET role = 'ADMIN' WHERE email = '$legacyEmail';"
  $null = $sql | & docker compose -p $ProjectName --env-file $EnvFile -f $composeFile exec -T postgres sh -c 'psql -v ON_ERROR_STOP=1 -U $POSTGRES_USER -d $POSTGRES_DB' 2>&1
  $before = @(Invoke-Compose exec -T api node $bootstrap --list-admins)
  $listed = [bool]($before -match [regex]::Escape($legacyEmail))
  $revoke = Invoke-Compose exec -T api node $bootstrap --revoke --email $legacyEmail
  $revokeExit = $LASTEXITCODE
  $after = @(Invoke-Compose exec -T api node $bootstrap --list-admins)
  $evidence['listAdmins'] = ($before | Where-Object { $_ -match '@' }) -join ' | '
  $revoked = ($legacy.Status -eq 201) -and $listed -and $revokeExit -eq 0 -and -not ($after -match [regex]::Escape($legacyEmail)) -and [bool]($after -match [regex]::Escape($userEmail))
  Add-Result 'upgrade review: --list-admins recorded, unapproved admin revoked' $revoked ("listed=$listed revoke exit=$revokeExit")

  # The check's own administrator is synthetic: revoke it so the kept volume
  # lets the next run bootstrap again.
  $null = Invoke-Compose exec -T api node $bootstrap --revoke --email $userEmail
  $finalAdmins = @(Invoke-Compose exec -T api node $bootstrap --list-admins | Where-Object { $_ -match '@' })
  Add-Result 'synthetic administrator revoked after the check' ($finalAdmins.Count -eq 0) ("administrators left: $($finalAdmins.Count)")

  # -------------------------------------------------------------------------
  # 11. Restart and persistence (SC-013)
  # -------------------------------------------------------------------------
  $description = "release-check-$runId"
  $created = Invoke-Http "$PublicOrigin/api/transactions" -Method POST -CookieJar $jar -Body (@{
      amount = 123456; currency = 'VND'; direction = 'EXPENSE'
      transactionTime = [DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ss.fffZ'); description = $description
    } | ConvertTo-Json -Compress)
  Add-Result 'create a transaction through the proxy' ($created.Status -eq 201) ("status $($created.Status)")

  function Get-TransactionCount {
    $null = Invoke-Http "$PublicOrigin/api/auth/login" -Method POST -Body $credentials -CookieJar $jar
    $list = Invoke-Http "$PublicOrigin/api/transactions?search=$description" -CookieJar $jar
    $data = Get-Prop (ConvertFrom-JsonSafe $list.Body) 'data'
    $items = if ($data -is [array]) { $data } elseif (Get-Prop $data 'items') { Get-Prop $data 'items' } else { Get-Prop $data 'data' }
    return @(@($items) | Where-Object { $_ -and (Get-Prop $_ 'description') -eq $description }).Count
  }

  $null = Invoke-Compose restart api
  $back = Wait-Until { (Invoke-Http "$loopbackApi/health/ready").Status -eq 200 } 120 3
  $countAfterRestart = Get-TransactionCount
  Add-Result 'API restart: account and one transaction persist' ($back -and $countAfterRestart -eq 1) ("ready=$back count=$countAfterRestart")

  $null = Invoke-Compose down
  $null = Invoke-Compose up -d
  $back = Wait-Until { (Invoke-Http "$loopbackApi/health/ready").Status -eq 200 } 180 3
  $null = Wait-Until { (Invoke-Http "$PublicOrigin/api/health/ready").Status -eq 200 } 60 3
  $countAfterRecreate = Get-TransactionCount
  Add-Result 'down/up (volumes kept): no loss, no duplicates' ($back -and $countAfterRecreate -eq 1) ("ready=$back count=$countAfterRecreate")

  # -------------------------------------------------------------------------
  # 12. Dependency outage and recovery
  # -------------------------------------------------------------------------
  $null = Invoke-Compose stop postgres
  $notReady = Wait-Until { (Invoke-Http "$loopbackApi/health/ready").Status -eq 503 } 60 2
  $dataCall = Invoke-Http "$PublicOrigin/api/transactions" -CookieJar $jar
  Add-Result 'outage: readiness 503 while PostgreSQL is down' $notReady
  Add-Result 'outage: data call 503 SERVICE_UNAVAILABLE' ($dataCall.Status -eq 503 -and (Get-ErrorCode $dataCall) -eq 'SERVICE_UNAVAILABLE') ("status $($dataCall.Status), code $(Get-ErrorCode $dataCall)")
  $null = Invoke-Compose start postgres
  $recovered = Wait-Until { (Invoke-Http "$loopbackApi/health/ready").Status -eq 200 } 120 3
  $dataAgain = Invoke-Http "$PublicOrigin/api/transactions" -CookieJar $jar
  Add-Result 'outage: recovery without an API restart' ($recovered -and $dataAgain.Status -eq 200) ("ready=$recovered data status $($dataAgain.Status)")

  # -------------------------------------------------------------------------
  # 13. Graceful shutdown
  # -------------------------------------------------------------------------
  # stdout only: a compose warning on stderr must not be taken for the id.
  $apiId = (& docker compose -p $ProjectName --env-file $EnvFile -f $composeFile ps -q api 2>$null | Where-Object { $_ -match '^[0-9a-f]{12,}$' } | Select-Object -First 1)
  $started = Get-Date
  $null = Invoke-Compose stop -t 30 api
  $apiContainerStopped = $true
  $elapsed = [math]::Round(((Get-Date) - $started).TotalSeconds, 1)
  $state = (& docker inspect -f '{{.State.ExitCode}} {{.State.OOMKilled}}' $apiId 2>$null | Out-String).Trim()
  $graceful = [bool]((& docker logs --tail 50 $apiId 2>&1 | Out-String) -match 'shut down gracefully')
  $exitCode = ($state -split ' ')[0]
  Add-Result 'graceful shutdown on SIGTERM' ($graceful -and $exitCode -ne '137' -and $elapsed -lt 30) ("exit $exitCode after ${elapsed}s; graceful log=$graceful")
}
catch {
  Add-Result 'verification aborted' $false ($_.Exception.Message)
}
finally {
  foreach ($step in $cleanup) { & $step }
  if (-not $KeepRunning) { $null = Invoke-Compose down }
  elseif ($apiContainerStopped) { $null = Invoke-Compose up -d }
  Remove-Item -Recurse -Force $workDir -ErrorAction SilentlyContinue
}

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
Write-Host ''
Write-Host 'Release verification (T100)'
foreach ($key in $evidence.Keys) { Write-Host ("  {0}: {1}" -f $key, $evidence[$key]) }
$results | Format-Table -AutoSize -Wrap | Out-String -Width 200 | Write-Host
$failed = @($results | Where-Object { $_.Result -eq 'FAIL' }).Count
Write-Host ("{0} checks, {1} failed; volumes kept ({2}_cashlens_prod_postgres_data)" -f $results.Count, $failed, $ProjectName)
if ($failed -gt 0) {
  Write-Host 'RESULT: FAIL'
  exit 1
}
if ($authoritative) {
  Write-Host 'RESULT: PASS (authoritative: reference release host)'
  exit 0
}
Write-Host 'RESULT: PASS (INFORMATIVE ONLY: not the reference release host; this is not the release gate)'
exit 3
