import { createTestApp } from './helpers/test-app'; // first: seeds synthetic config
import { INestApplication } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import request from 'supertest';
import { App } from 'supertest/types';
import { DashboardRepository } from '../src/modules/dashboard/dashboard.repository';
import { GmailApiService } from '../src/modules/email-ingestion/gmail-api.service';
import { PrismaService } from '../src/prisma/prisma.service';
import {
  TestUser,
  absentId,
  cleanupUsers,
  dataOf,
  idPath,
  registerUser,
} from './helpers/auth-fixtures';
import {
  createGmailConnection,
  createListenRule,
} from './helpers/email-fixtures';

jest.setTimeout(120_000);

/**
 * T092 (ERR-001, ERR-002, ERR-004, ERR-006): the API error and success
 * contracts (contracts/openapi.yaml `Error` and `Envelope`).
 *
 * - Every error body keeps the Nest shape (`statusCode`, `message`, `error`)
 *   and adds a stable `code`, a `correlationId`, and, for validation
 *   failures, `fields`. It never carries a stack, an exception class, SQL,
 *   provider text, or a secret.
 * - Every success body is `{success, data, message, timestamp}` plus the
 *   additive `correlationId`.
 * - The correlation id is generated by the server for every request (the
 *   spec allows no client-supplied id), is opaque, and is also returned in
 *   the `x-correlation-id` response header.
 */

const UUID =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

/** Material that must never appear in any error response. */
const FORBIDDEN = [
  /\bat [\w.<>]+ \(/, // stack frame
  /stack/i,
  /Prisma/,
  /SELECT |INSERT |UPDATE "|FROM "/,
  /node_modules/,
  /\.ts:\d+/,
  /synthetic-leak-secret/,
];

const ERROR_KEYS = new Set([
  'statusCode',
  'message',
  'error',
  'code',
  'correlationId',
  'fields',
]);

type ErrorBody = {
  statusCode: number;
  message: string | string[];
  error?: string;
  code: string;
  correlationId: string;
  fields?: Record<string, string[]>;
};

/** Asserts the safe error shape and returns the body. */
const expectSafeError = (
  res: request.Response,
  status: number,
  code: string,
): ErrorBody => {
  expect(res.status).toBe(status);
  const body = res.body as ErrorBody;
  expect(body.statusCode).toBe(status);
  expect(body.code).toBe(code);
  expect(body.correlationId).toMatch(UUID);
  expect(res.headers['x-correlation-id']).toBe(body.correlationId);
  expect(typeof body.message === 'string' || Array.isArray(body.message)).toBe(
    true,
  );
  for (const key of Object.keys(body)) expect(ERROR_KEYS.has(key)).toBe(true);
  const text = JSON.stringify(body);
  for (const pattern of FORBIDDEN) expect(text).not.toMatch(pattern);
  return body;
};

const expectEnvelope = (res: request.Response) => {
  const body = res.body as Record<string, unknown>;
  expect(Object.keys(body).sort()).toEqual([
    'correlationId',
    'data',
    'message',
    'success',
    'timestamp',
  ]);
  expect(body).toMatchObject({ success: true, message: 'Success' });
  expect(new Date(body.timestamp as string).toISOString()).toBe(body.timestamp);
  expect(body.correlationId).toMatch(UUID);
  expect(res.headers['x-correlation-id']).toBe(body.correlationId);
  return body.data;
};

describe('API error and envelope contract (T092)', () => {
  let app: INestApplication<App>;
  let prisma: PrismaService;
  let alice: TestUser;
  let bob: TestUser;
  const http = () => request(app.getHttpServer());

  beforeAll(async () => {
    app = await createTestApp();
    prisma = app.get(PrismaService);
    alice = await registerUser(app, 't092-alice');
    bob = await registerUser(app, 't092-bob');
  });

  afterAll(async () => {
    jest.restoreAllMocks();
    if (prisma) await cleanupUsers(prisma, [alice?.id, bob?.id]);
    await app?.close();
  });

  describe('errors', () => {
    it('400 validation: stable code, the Nest messages, and per-field errors', async () => {
      const res = await alice.agent
        .post('/api/transactions')
        .send({ amount: -5, direction: 'SIDEWAYS', transactionTime: 'soon' });
      const body = expectSafeError(res, 400, 'VALIDATION_FAILED');
      expect(body.error).toBe('Bad Request');
      expect(Array.isArray(body.message)).toBe(true);
      expect(Object.keys(body.fields ?? {}).sort()).toEqual(
        expect.arrayContaining(['amount', 'direction', 'transactionTime']),
      );
      for (const messages of Object.values(body.fields ?? {})) {
        expect(messages.length).toBeGreaterThan(0);
      }
      // The flat message list is unchanged: every field message is in it.
      for (const messages of Object.values(body.fields ?? {})) {
        for (const text of messages) expect(body.message).toContain(text);
      }
    });

    it('400 for an unknown field names that field', async () => {
      const res = await alice.agent.post('/api/transactions').send({
        amount: 1,
        direction: 'EXPENSE',
        transactionTime: new Date().toISOString(),
        sneaky: true,
      });
      const body = expectSafeError(res, 400, 'VALIDATION_FAILED');
      expect(body.fields).toHaveProperty('sneaky');
    });

    it('400 for a body that is not valid JSON, without quoting the body', async () => {
      const res = await alice.agent
        .post('/api/transactions')
        .set('content-type', 'application/json')
        .send('{"token": synthetic-leak-secret-abc,');
      const body = expectSafeError(res, 400, 'BAD_REQUEST');
      expect(body.message).toBe('Request body is not valid JSON');
    });

    it('keeps an existing application code (400 RAW_EMAIL_BODY_UNAVAILABLE)', async () => {
      const res = await alice.agent
        .patch('/api/users/me/settings')
        .send({ storeRawEmailBody: true });
      expectSafeError(res, 400, 'RAW_EMAIL_BODY_UNAVAILABLE');
    });

    it('401 without a session', async () => {
      const res = await http().get('/api/transactions');
      const body = expectSafeError(res, 401, 'UNAUTHORIZED');
      expect(body.message).toBe('Unauthorized');
    });

    it('401 for a forged access token, without echoing it', async () => {
      const forged =
        'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4In0.synthetic-leak-secret';
      const res = await http()
        .get('/api/transactions')
        .set('Cookie', `accessToken=${forged}`);
      expectSafeError(res, 401, 'UNAUTHORIZED');
      expect(JSON.stringify(res.body)).not.toContain(forged);
    });

    it('403 for a non-administrator on an administrator route', async () => {
      const res = await alice.agent.post('/api/users/list').send({});
      expectSafeError(res, 403, 'FORBIDDEN');
    });

    it("404 owner-safe: another owner's id and an absent id look the same", async () => {
      const own = dataOf<{ id: string }>(
        await alice.agent
          .post('/api/transactions')
          .send({
            amount: 1000,
            direction: 'EXPENSE',
            transactionTime: new Date().toISOString(),
          })
          .expect(201),
      ).id;
      const foreign = await bob.agent.get(`/api/transactions/${idPath(own)}`);
      const absent = await bob.agent.get(
        `/api/transactions/${idPath(absentId())}`,
      );
      const a = expectSafeError(foreign, 404, 'NOT_FOUND');
      const b = expectSafeError(absent, 404, 'NOT_FOUND');
      expect({ ...a, correlationId: '' }).toEqual({ ...b, correlationId: '' });
      expect(a.correlationId).not.toBe(b.correlationId);
    });

    it('404 for an unknown route and for an encoded NUL', async () => {
      const unknown = expectSafeError(
        await http().get('/api/no-such-route?token=synthetic-leak-secret'),
        404,
        'NOT_FOUND',
      );
      expect(unknown.message).toBe('Cannot GET /api/no-such-route');
      expectSafeError(
        await http().get('/api/transactions/a%00b'),
        404,
        'NOT_FOUND',
      );
    });

    it('409 keeps its application code (ALERT_RESOLVED)', async () => {
      const alert = await prisma.alert.create({
        data: {
          userId: alice.id,
          type: 'SYSTEM',
          title: 'T092',
          message: 'T092',
          status: 'RESOLVED',
          conditionKey: `t092:${alice.id}`,
        },
      });
      const res = await alice.agent.patch(
        `/api/alerts/${idPath(alert.id)}/dismiss`,
      );
      const body = expectSafeError(res, 409, 'ALERT_RESOLVED');
      expect(body.error).toBe('Conflict');
    });

    it('503 keeps its application code (RECONNECT_REQUIRED)', async () => {
      const connection = await createGmailConnection(app, alice.id, 't092-exp');
      await prisma.emailConnection.update({
        where: { id: connection.id },
        data: { status: 'EXPIRED' },
      });
      const res = await alice.agent.post(
        `/api/email-connections/${idPath(connection.id)}/sync`,
      );
      expectSafeError(res, 503, 'RECONNECT_REQUIRED');
    });

    it('503 for a database outage, with a safe message', async () => {
      jest
        .spyOn(app.get(DashboardRepository), 'financialContext')
        .mockRejectedValueOnce(
          new Prisma.PrismaClientInitializationError(
            "Can't reach database server at `db.internal:5432` synthetic-leak-secret",
            '7.7.0',
          ),
        );
      const res = await alice.agent.get('/api/dashboard/overview');
      const body = expectSafeError(res, 503, 'SERVICE_UNAVAILABLE');
      expect(body.message).toBe('Service temporarily unavailable');
      expect(JSON.stringify(body)).not.toContain('db.internal');
    });

    it('500 for an unexpected failure: a generic message and nothing internal', async () => {
      jest
        .spyOn(app.get(DashboardRepository), 'financialContext')
        .mockRejectedValueOnce(
          new Error(
            'boom: password=synthetic-leak-secret at /srv/app/dashboard.service.ts:42',
          ),
        );
      const res = await alice.agent.get('/api/dashboard/overview');
      const body = expectSafeError(res, 500, 'INTERNAL_ERROR');
      expect(body.message).toBe('Internal server error');
      expect(JSON.stringify(body)).not.toContain('boom');
    });

    it('500 for an unexpected Prisma error, with no query or constraint detail', async () => {
      jest
        .spyOn(app.get(DashboardRepository), 'financialContext')
        .mockRejectedValueOnce(
          new Prisma.PrismaClientKnownRequestError(
            'Unique constraint failed on the fields: (`email`) synthetic-leak-secret',
            { code: 'P2002', clientVersion: '7.7.0' },
          ),
        );
      const res = await alice.agent.get('/api/dashboard/overview');
      const body = expectSafeError(res, 500, 'INTERNAL_ERROR');
      expect(JSON.stringify(body)).not.toMatch(/P2002|constraint|email/);
    });
  });

  describe('correlation ids', () => {
    it('are generated per request and never taken from the client', async () => {
      const spoof = 'attacker-chosen-id';
      const res = await alice.agent
        .get('/api/alerts/unread-count')
        .set('x-correlation-id', spoof)
        .set('x-request-id', spoof)
        .expect(200);
      const id = (res.body as { correlationId: string }).correlationId;
      expect(id).toMatch(UUID);
      expect(id).not.toBe(spoof);
      const again = await alice.agent.get('/api/alerts/unread-count');
      expect((again.body as { correlationId: string }).correlationId).not.toBe(
        id,
      );
    });

    it('are also on health responses, which keep their status codes', async () => {
      const res = await http().get('/api/health/ready').expect(200);
      expect(expectEnvelope(res)).toEqual({ status: 'ready', database: 'up' });
      expectEnvelope(await http().get('/api/health/live').expect(200));
    });
  });

  describe('success envelope', () => {
    it('ordinary CRUD (transaction create and read)', async () => {
      const created = await alice.agent
        .post('/api/transactions')
        .send({
          amount: 2500,
          direction: 'EXPENSE',
          transactionTime: new Date().toISOString(),
        })
        .expect(201);
      const data = expectEnvelope(created) as { id: string };
      expectEnvelope(
        await alice.agent
          .get(`/api/transactions/${idPath(data.id)}`)
          .expect(200),
      );
    });

    it('a Gmail sync run', async () => {
      const connection = await createGmailConnection(
        app,
        alice.id,
        't092-sync',
      );
      await createListenRule(alice.agent, {
        connectionId: connection.id,
        senderEmail: 'notify@vcb.example.test',
        bankProviderId: 'bank_vcb',
      });
      jest
        .spyOn(app.get(GmailApiService), 'listMessageIds')
        .mockResolvedValueOnce({ ids: [] });
      const res = await alice.agent
        .post(`/api/email-connections/${idPath(connection.id)}/sync`)
        .expect(201);
      expect(expectEnvelope(res)).toMatchObject({ status: 'SUCCESS' });
    });

    it('a goal feasibility result', async () => {
      const goal = dataOf<{ id: string }>(
        await alice.agent
          .post('/api/goals')
          .send({ name: 'T092', targetAmount: 1_000_000 })
          .expect(201),
      );
      const res = await alice.agent
        .get(`/api/goals/${idPath(goal.id)}/simulation`)
        .expect(200);
      expect(expectEnvelope(res)).toMatchObject({
        goalId: goal.id,
        status: 'INSUFFICIENT_DATA',
      });
    });

    it('alert responses (list, unread count, settings)', async () => {
      expectEnvelope(await alice.agent.get('/api/alerts').expect(200));
      expect(
        expectEnvelope(
          await alice.agent.get('/api/alerts/unread-count').expect(200),
        ),
      ).toEqual({ count: expect.any(Number) as number });
      expectEnvelope(await alice.agent.get('/api/alerts/settings').expect(200));
    });
  });
});
